/*
 * This source file was generated by the Gradle 'init' task
 */
package hgu.isel;

import hgu.isel.analyzer.ByteAnalyzer;
import hgu.isel.options.CommandLineOptions;
import hgu.isel.reader.ByteReader;
import hgu.isel.tokenizer.ByteStructure;
import hgu.isel.tokenizer.ByteTokenizer;


import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.ParseException;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import java.util.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;

public class ByteTok {
    private static HashSet<String> customAttributes = new HashSet<>();

    public static void main(String[] args) {
        ByteTok parser = new ByteTok();
        parser.run(args);
    }

    public void run(String[] args) {
        CommandLineOptions commandLineOptions = new CommandLineOptions();

        try {
            CommandLine cmd = commandLineOptions.parse(args);

            if(cmd.hasOption("v")) {

                String[] vocabArgs = cmd.getOptionValues("v");
                String inputPath = vocabArgs[0];
                int maximumSize = Integer.parseInt(vocabArgs[1]);
                String vocabPath = vocabArgs[2];

                createVocabulary(inputPath, maximumSize, vocabPath);

            } else if(cmd.hasOption("a")) {

                String[] tokenizeArgs = cmd.getOptionValues("a");
                analyze(tokenizeArgs[0]);

            } else if (cmd.hasOption("j")) {
                String[] tokenizeArgs = cmd.getOptionValues("j");
                String classFile = tokenizeArgs[0];
                String outDir = tokenizeArgs[1];
                
                saveJson(classFile, outDir);

            } else if (cmd.hasOption("jd")) {
               
                String[] tokenizeArgs = cmd.getOptionValues("jd");
                String classListFile = tokenizeArgs[0];
                String outDir = tokenizeArgs[1];

                try (BufferedReader br = new BufferedReader(new FileReader(classListFile))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String classFile = line.trim();
                        String base = new File(classFile).getName().replace(".class", "");
                        File jsonFile = new File(outDir, base + ".json");

                        // 이미 JSON이 있으면 건너뛰기
                        if (jsonFile.exists()) {
                            continue;
                        }

                        saveJson(classFile, outDir);
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }

            } else if(cmd.hasOption("r")) {

                String[] removeArgs = cmd.getOptionValues("r");
                String inputPath = removeArgs[0];

                remove(inputPath);

            } else if(cmd.hasOption("g")) {

                String[] generateArgs = cmd.getOptionValues("g");
                String inputPath = generateArgs[0];
                String directory = generateArgs[1];

                generate(inputPath, directory);

            } else if(cmd.hasOption("d")) {

                String[] deleteArgs = cmd.getOptionValues("d");
                String inputPath = deleteArgs[0];

                delete(inputPath);

            } else if(cmd.hasOption("f")) {

                String[] findArgs = cmd.getOptionValues("f");
                String inputPath = findArgs[0];

                findCustomizedAttributes(inputPath);

            } else if(cmd.hasOption("e")) {

                String[] extractArgs = cmd.getOptionValues("e");
                String inputPath = extractArgs[0];
                String directory = extractArgs[1];

                extract(inputPath, directory);

            } else if(cmd.hasOption("s")) {
                String[] searchArgs = cmd.getOptionValues("s");
                String inputPath = searchArgs[0];
                String methodName = searchArgs[1];
                String outputDirectory = searchArgs[2];

                findMethodWithSignature(inputPath, methodName, outputDirectory);
            } else if(cmd.hasOption("sc")) {
                String[] searchArgs = cmd.getOptionValues("sc");

                ArrayList<String> pathList = new ArrayList<>();
                ArrayList<String> classNameList = new ArrayList<>();
                ArrayList<String> methodNameList = new ArrayList<>();
                int count = 0;


                try (BufferedReader br = new BufferedReader(new FileReader(searchArgs[0]))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] values = line.split(",");

                        if (values.length >= 3) {
                            String path = values[0].trim();
                            String className = values[1].trim();
                            String methodName = values[2].trim();

                            pathList.add(path);
                            classNameList.add(className);
                            methodNameList.add(methodName);

                            count++;
                        }
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }

                for(int i = 0; i < count; i++) {
                    String inputPath = pathList.get(i) + "/" + classNameList.get(i) + ".class";
                    String methodName = methodNameList.get(i);
                    String outputDirectory = searchArgs[1];

                    findMethodWithSignature(inputPath, methodName, outputDirectory);
                }
            }

        } catch (ParseException e) {
            System.out.println("옵션 파싱 에러: " + e.getMessage());
            commandLineOptions.printHelp();
        }

    }

    private void createVocabulary(String path, int maximumSize, String vocabPath) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        ByteTokenizer byteTokenizer = new ByteTokenizer();


        for(String s : filePaths) {
            byte[] bytes;
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                ByteStructure byteStructure = byteAnalyzer.analyze();
                int hashSize = byteTokenizer.saveTokens(byteStructure);

                if(hashSize > maximumSize) { // up to maximum size
                    break;
                }

            } catch (Exception e) {
                e.printStackTrace();
                System.exit(0);
            }

        }
        System.out.println("Success creating vocab");
        byteTokenizer.createVocabulary(vocabPath);
    }

    private void analyze(String path) {
        ByteReader byteReader = new ByteReader(path);

        byte[] bytes = byteReader.readClassFile();

        ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
        ByteStructure byteStructure = null;
        try {
            byteStructure = byteAnalyzer.analyze();
            String resultText = byteStructure.toString();

            String normalizedPath = path.replace("\\", "/"); 
            String key = "resources/";
            int mainIndex = normalizedPath.lastIndexOf(key);
            String relativePath;
            if (mainIndex != -1) {
                relativePath = normalizedPath.substring(mainIndex + key.length());
            } else {
                relativePath = Paths.get(path).getFileName().toString();
            }
            String txtFileName = relativePath
                    .replace("/", ".")
                    .replace(".class", ".txt");

            Path outputDir = Paths.get(System.getProperty("user.dir"), "output");
            Files.createDirectories(outputDir);
            Path outputPath = outputDir.resolve(txtFileName);

            Files.write(outputPath,
                        resultText.getBytes(StandardCharsets.UTF_8),
                        StandardOpenOption.CREATE,
                        StandardOpenOption.TRUNCATE_EXISTING);

            if (Files.exists(outputPath)) {
                System.out.println("File saved : " + outputPath.toAbsolutePath());
            } else {
                System.err.println("File not saved!");
            }

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }


    private void saveJson(String path, String outOption) {
        ByteReader byteReader = new ByteReader(path);
        byte[] bytes = byteReader.readClassFile();

        ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
        try {
            // 1. byteAnalyzer.analyze()를 통해 ByteStructure '객체(인스턴스)'를 얻음
            ByteStructure byteStructure = byteAnalyzer.analyze();

            String classFileName = Paths.get(path).getFileName().toString();
            String jsonFileName = classFileName.replace(".class", ".json");

            Path outputDir = Paths.get(outOption);
            Files.createDirectories(outputDir);
            Path outputPath = outputDir.resolve(jsonFileName);

            Gson gson = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
            
            // 2. 클래스명(ByteStructure)이 아닌 변수명(byteStructure)으로 toJson() 호출!
            JsonElement jsonElement = byteStructure.toJson();

            Files.write(outputPath,
                    gson.toJson(jsonElement).getBytes(StandardCharsets.UTF_8),
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING);

            if (Files.exists(outputPath)) {
                System.out.println("File saved : " + outputPath.toAbsolutePath());
            } else {
                System.err.println("File not saved!");
            }

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }


    private void remove(String path) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        byte[] bytes;

        for(String s : filePaths) {
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                byteAnalyzer.analyze();
                System.out.println("Success!! : " + s);
            } catch (Exception e) {
                try {
                    Path filePath = Paths.get(s);
                    Files.delete(filePath);
                    System.out.println("Deleted file: " + s);
                } catch (IOException deleteException) {
                    System.err.println("Failed to delete file: " + s);

                }
            }
        }
    }

    private void generate(String path, String directory) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        byte[] bytes;
        ByteTokenizer byteTokenizer = new ByteTokenizer();

        for(String s : filePaths) {
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                ByteStructure byteStructure = byteAnalyzer.analyze();
                byteStructure.setFileName(s);

                byteTokenizer.generateNewFilesWithConstantPool(byteStructure, directory);

                System.out.println("Success: " + s);
            } catch (Exception e) {
                System.out.println("Failed: " + s);
                e.printStackTrace();
            }


        }
    }

    private void delete(String path) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        byte[] bytes;
        ByteTokenizer byteTokenizer = new ByteTokenizer();

        for(String s : filePaths) {
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                ByteStructure byteStructure = byteAnalyzer.analyze();
                byteStructure.setFileName(s);

                boolean isDelete = byteTokenizer.removeFiles(byteStructure);

                if(isDelete) {
                    Path filePath = Paths.get(s);
                    Files.delete(filePath);

                    System.out.println("delete " + s);
                }
                System.out.println("not delete");


            } catch (Exception e) {

                e.printStackTrace();
            }
        }
    }

    private void findCustomizedAttributes(String path) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        byte[] bytes;


        for(String s : filePaths) {
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                byteAnalyzer.analyze();
            } catch (Exception e) {
                String attributeName = e.getMessage();
                System.out.println("new attribute: " + attributeName);
                customAttributes.add(attributeName);
            }
        }
    }

    private void extract(String path, String directory) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        byte[] bytes;
        ByteTokenizer byteTokenizer = new ByteTokenizer();

        for(String s : filePaths) {
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                ByteStructure byteStructure = byteAnalyzer.analyze();
                byteStructure.setFileName(s);

                byteTokenizer.generateNewFiles(byteStructure, directory);

                System.out.println("Success: " + s);
            } catch (Exception e) {
                System.out.println("Failed: " + s);
                e.printStackTrace();
            }
        }
    }

    private void findMethodWithSignature(String path, String methodName, String directory) {
        ByteReader byteReader = new ByteReader(path);
        List<String> filePaths = byteReader.readClassFilePaths();

        byte[] bytes;
        ByteTokenizer byteTokenizer = new ByteTokenizer();

        for(String s : filePaths) {
            bytes = byteReader.readClassFile(s);

            ByteAnalyzer byteAnalyzer = new ByteAnalyzer(bytes);
            try {
                ByteStructure byteStructure = byteAnalyzer.analyze();
                byteStructure.setFileName(s);

                byteTokenizer.findSpecificMethod(byteStructure, methodName, directory);

                System.out.println("Success: " + s);
            } catch (Exception e) {
                System.out.println("Failed: " + s);
                e.printStackTrace();
            }
        }
    }




    public static HashSet<String> getCustomAttributes() {
        return customAttributes;
    }

    public static void setCustomAttributes(HashSet<String> customAttributes) {
        ByteTok.customAttributes = customAttributes;
    }
}
